var namespace_yodiwo_1_1_a_p_i_1_1_media_streaming =
[
    [ "AudioAuthenticationRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_authentication_request.html", null ],
    [ "AudioAuthenticationResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_authentication_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_authentication_response" ],
    [ "AudioData", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_data.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_data" ],
    [ "AudioDataReq", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_data_req.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_data_req" ],
    [ "AudioDataResp", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_data_resp.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_data_resp" ],
    [ "AudioMediaDescriptor", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_media_descriptor.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_media_descriptor" ],
    [ "AudioServerConnectRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_connect_request.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_connect_request" ],
    [ "AudioServerConnectResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_connect_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_connect_response" ],
    [ "AudioServerDisconnectRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_disconnect_request.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_disconnect_request" ],
    [ "AudioServerDisconnectResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_disconnect_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_disconnect_response" ],
    [ "AudioServerFeedRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_feed_request.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_feed_request" ],
    [ "AudioServerFeedResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_feed_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_audio_server_feed_response" ],
    [ "ErrorMessage", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_error_message.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_error_message" ],
    [ "InfoMessage", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_info_message.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_info_message" ],
    [ "OngoingMediaStreamDescriptor", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_ongoing_media_stream_descriptor.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_ongoing_media_stream_descriptor" ],
    [ "VideoAuthenticationRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_authentication_request.html", null ],
    [ "VideoAuthenticationResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_authentication_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_authentication_response" ],
    [ "VideoData", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_data.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_data" ],
    [ "VideoDataReq", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_data_req.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_data_req" ],
    [ "VideoDataResp", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_data_resp.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_data_resp" ],
    [ "VideoDescriptor", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_descriptor.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_descriptor" ],
    [ "VideoMediaDescriptor", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_media_descriptor.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_media_descriptor" ],
    [ "VideoServerConnectRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_connect_request.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_connect_request" ],
    [ "VideoServerConnectResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_connect_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_connect_response" ],
    [ "VideoServerDisconnectRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_disconnect_request.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_disconnect_request" ],
    [ "VideoServerDisconnectResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_disconnect_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_disconnect_response" ],
    [ "VideoServerFeedRequest", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_feed_request.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_feed_request" ],
    [ "VideoServerFeedResponse", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_feed_response.html", "class_yodiwo_1_1_a_p_i_1_1_media_streaming_1_1_video_server_feed_response" ]
];