# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'YodiwoHub' do

# MQTT client library
pod 'MQTTKit', :git => 'https://github.com/mobile-web-messaging/MQTTKit.git'

# Toast-like notifications library
pod 'TWMessageBarManager'

# JSON serdes library
pod 'JSONModel'

end

target 'YodiwoHubTests' do

end

